### ISSUE TITLE
How was your week end?

### ISSUE THREAD

**Issue by brutalcrozt** [as1ndu/AMA#1]
:smile_cat:

**Comment by as1ndu** [comment]
It was fine. thank God i have finaly seen thiss.

**Comment by brutalcrozt** [comment]
we are both cat :smile_cat: 
let's be a friend. i already add you on fb follow on twitter and github.
are you a coder?

**Comment by as1ndu** [comment]
yeah, Js and python

**Comment by brutalcrozt** [comment]
wow, that cool. I just decide want learn python too

**Comment by as1ndu** [comment]
A glad u did. its a fantastic language!

**Comment by brutalcrozt** [comment]
:smirk_cat:
